# Generated by Django 4.2 on 2023-07-02 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsPortal', '0002_category_subscribers_postsubscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsubscribers',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postsubscribers',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
